language: java
services:
  - docker
addons:
    firefox: "45.4.0esr"
install: mvn install -DskipTests -Dgpg.skip
jdk:
  - oraclejdk8
env:
  - DISPLAY=:99
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - mvn verify -Dgpg.skip=true -Dgalen.use.fail.exit.code=false -Dwebdriver.gecko.driver=$PWD/geckodriver/geckodriver
before_install:
  - docker pull selenium/hub
  - docker pull selenium/node-chrome
  - docker pull selenium/node-firefox
  - docker pull selenium/node-phantomjs
  - docker run -d -p 4444:4444 -e SE_OPTS="-debug true" --name selenium-hub selenium/hub:3.2.0-actinium
  - docker run -d --link selenium-hub:hub --name node-chrome selenium/node-chrome:3.2.0-actinium
  - docker run -d --link selenium-hub:hub --name node-firefox selenium/node-firefox:3.2.0-actinium
  - docker run -d --link selenium-hub:hub --name node-phantomjs selenium/node-phantomjs:3.2.0-actinium
  - docker ps -a
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 +extension RANDR -ac -screen 0 1280x1024x16"
after_failure:
  - find . -name "TestSuite.txt" | xargs cat
